#!/bin/bash
. ./util_f
. ./...

latest_ok=$(grep "Status: OK" tests.status 2>/dev/null | tail -n 1)

if [ -z "$latest_ok" ]; then
    echo "No OK tests found in tests.status"
    exit 1
fi

test_date=$(echo "$latest_ok" | cut -d'|' -f1 | xargs)
version=$(echo "$latest_ok" | cut -d'|' -f2 | cut -d':' -f2 | xargs)
iso_name=$(echo "$latest_ok" | cut -d'|' -f3 | cut -d':' -f2 | xargs)
iso_size=$(echo "$latest_ok" | cut -d'|' -f4 | cut -d':' -f2 | xargs)

kernel_version=$(uname -r | cut -d'-' -f1)

sed -i '/<div>/,/<\/div>/d' README.md

awk -v version="$version" -v test_date="$test_date" -v iso_name="$iso_name" -v iso_size="$iso_size" -v kernel="$kernel_version" '
/^# Vase$/ {
    print
    print ""
    print "<div>"
    print "    <img src=\"./vase.svg\" alt=\"VaseLogo\" width=\"72\">"
    print "    <a href=\"https://github.com/h8d13/Vase/releases\">"
    print "        <img src=\"https://img.shields.io/badge/Arch_Linux-v" kernel "-darkgreen\" alt=\"Arch\">"
    print "    </a>"
    print "    <br><br>"
    print "    <strong>Version:</strong> " version " | <strong>Tested:</strong> " test_date " | <strong>Size:</strong> " iso_size
    print "    <br><br>"
    print "    <a href=\"https://github.com/h8d13/Vase/releases\">Releases</a>"
    print "</div>"
    getline
    if ($0 != "") print
    next
}
{ print }
' README.md > README.md.tmp && mv README.md.tmp README.md

echo "README updated with latest release: ${version} (Kernel: ${kernel_version})"
