#!/bin/bash
set -e  # Exit on error

#klagan_mode="-desktop" # saves 1gb by not downloading as many plasma stuff

echo "=== Updating system ==="
pacman -Syu --noconfirm

echo "=== Installing KDE Plasma ==="
pacman -S --noconfirm --needed plasma${klagan_mode} wayland sddm plasma-nm

echo "=== Installing audio support ==="
pacman -S --noconfirm --needed pipewire pipewire-alsa pipewire-pulse pipewire-jack wireplumber

#echo "=== Installing Bluetooth support ==="
#pacman -S --noconfirm bluez bluez-runit bluez-utils bluedevil
# ln -sf /etc/runit/sv/bluetoothd /run/runit/service/

echo "=== Installation complete! ==="

echo "=== Enabling services! ==="
ln -sf /etc/runit/sv/sddm /run/runit/service/
ln -sf /etc/runit/sv/networkmanager /run/runit/service/


