#!/bin/bash
set -e  # Exit on error

############## DESKTOP THINGS

# Exmaple of what i'd install on an Intel/Intel PC
#KLAGAN_MODE="-desktop" # saves 1gb by not downloading as many plasma stuff

echo "=== Updating system ==="
pacman -Syu --noconfirm

echo "=== Installing KDE Plasma ==="
pacman -S --noconfirm --needed plasma${KLAGAN_MODE} wayland sddm sddm-runit plasma-nm

# nice to haves
#pacman -S --noconfirm --needed konsole ark dolphin
# or full apps (heavy)
#pacman -S kde-applications

echo "=== Installing audio support ==="
pacman -S --noconfirm --needed pipewire-alsa #pipewire #pipewire-pulse #pipewire-jack #wireplumber

#echo "=== Installing Bluetooth support ==="
#pacman -S --noconfirm bluez bluez-runit bluez-utils bluedevil
# ln -sf /etc/runit/sv/bluetoothd /run/runit/service/

# hardware
# pacman -S ${HW_GROUP_INTELINTEL}

echo "=== Installation complete! ==="

echo "=== Enabling services! ==="
ln -sf /etc/runit/sv/sddm /run/runit/service/
