#!/bin/bash
set -e  # Exit on error

############## DESKTOP CFG
#KLAGAN_MODE="-desktop" 
# Uncomment saves 1gb by not downloading as many plasma stuff
# plasma contains flatpak for example while plasma-desktop doesn't. so discover will be useless

echo "=== Updating system ==="
pacman -Syu --noconfirm

echo "=== Installing KDE Plasma ==="
pacman -S --noconfirm --needed plasma${KLAGAN_MODE} wayland sddm sddm-runit plasma-nm
pacman -S --noconfirm --needed konsole ark dolphin

# nice to haves
# or full apps (heavy)
#pacman -S kde-applications

echo "=== Installing audio support ==="
pacman -S --noconfirm --needed pipewire-alsa #pipewire #pipewire-pulse #pipewire-jack #wireplumber

#mkdir -p /etc/pipewire
#cp /usr/share/pipewire/pipewire* /etc/pipewire
# edit final lines of 
#/etc/pipewire/pipewire.conf just before closing ]
# { path = "/usr/bin/wireplumber" args = ""}
# { path = "/usr/bin/pipewire" args= "-c pipewire-pulse.conf"}

# create in /home/usr/.config/autostart
#[Desktop Entry]
#Type=Application
#Name=Pipewire
#Exec=/usr/bin/pipewire
#X-KDE-autostart-phase=1

#echo "=== Installing Bluetooth support ==="
#pacman -S --noconfirm bluez bluez-runit bluez-utils bluedevil
# ln -sf /etc/runit/sv/bluetoothd /run/runit/service/

# hardware
# pacman -S ${HW_GROUP_INTELINTEL}

echo "=== Installation complete! ==="

echo "=== Enabling services! ==="
ln -sf /etc/runit/sv/sddm /run/runit/service/

