#!/bin/bash
# Edit /etc/pacman.conf for lib32
#HW_GROUP_INTELINTEL="lib32-mesa-dri lib32-libgl vulkan-intel lib32-vulkan-intel intel-media-driver"
# Steam will pull in a lot of 32bit libs but not hardware specific ones. Obviously since they only build for AMD hardware. 