#!/bin/sh
##Host packages needed
#pacman -S qemu-system-x86 qemu-img libvirt virglrenderer tigervnc
#qemu-full for other architectures

##Perms
#usermod -a -G kvm,libvirt $USER

#systemctl enable libvirtd.service
#systemctl start libvirtd.service

## Create disk
#qemu-img create -f qcow2 myvm.qcow2 30G

##QEMU with VirGL testing

## Boot
#qemu-system-x86_64 -enable-kvm -m 4G -cpu host -smp 8 -device virtio-vga-gl -display gtk,gl=on -cdrom arch.iso -hda myvm.qcow2 

## Run after install
#qemu-system-x86_64 -enable-kvm -m 4G -cpu host -smp 8 -device virtio-vga-gl -display gtk,gl=on -hda myvm.qcow2 

## Connect to display
# tigervnc :0 

# Guest gets: mesa mesa-dri mesa-vulkan-drivers vulkan-virtio qemu-guest-agent spice-vdagent libva-mesa-driver
# Test guest: glxinfo | grep -i mesa, vkcube, systemd-detect-virt
