#!/bin/sh
# Option 1: Just verify sig optional
# Find the mirror you used: https://archlinux.org/download/
# Click copy link on the version of the iso you found
mirror_url="https://mirror.tiguinet.net/arch/iso/2025.09.01/archlinux-x86_64.iso"
## Paste it up here as so mirror_url="https://mirror.tiguinet.net/arch/iso/2025.09.01/archlinux-x86_64.iso"
mirror_url_sig="${mirror_url}.sig"

wget $mirror_url_sig ./d/archlinux-x86_64.iso.sig
# You can also find one with an extra date https://mirror.tiguinet.net/arch/iso/2025.09.01/archlinux-2025.09.01-x86_64.iso
# Dowload ISO if not present & always sig
# Verify
# TODO Configure based on actual iso location source constants
# Check we have gpg avaiable
gpg --keyserver-options auto-key-retrieve --verify archlinux-x86_64.iso.sig ./d/archlinux-x86_64.iso
