#!/bin/bash

set -e

. "$(dirname "$0")/../../util_f"
. "$(dirname "$0")/../../..."

if file_ex "${rel}${p_lib}/${rcw_file}"; then
    # Source wrapper
    . "${rel}${p_lib}/${rcw_file}"
fi

SCRIPT_DIR="$(dirname "$0")"
OVERLAY_DIR="$SCRIPT_DIR/../hade_box"
PROFILE_DIR="$SCRIPT_DIR/archiso_profile"
WORK_DIR="$SCRIPT_DIR/archiso_work"
OUTPUT_DIR="$SCRIPT_DIR/a"
  
if ! dir_ex "$OVERLAY_DIR"; then
   die "Did not find overlay dir."
fi

info "Setting up archiso profile..."
#rm -rf "$PROFILE_DIR"
mkdir -p "$PROFILE_DIR"
# Use standard release engeneering profile (same as ISO)
cp -r /usr/share/archiso/configs/releng/* "$PROFILE_DIR"

info "Adding $OVERLAY_DIR to airootfs..."
## Main overlay is defined here we append to root "/" our "hade_box" folder. 
mkdir -p "$PROFILE_DIR/airootfs/root"

# We could for example overlay all the plasma files directly into the ISO too
# That would speedup install time considerably at the cost of a larger ISO
## We can do this by editing $PROFILE_DIR/packages.x86_64

cp -r "$OVERLAY_DIR" "$PROFILE_DIR/airootfs/root/"

info "Building ISO with mkarchiso..."
## Think of this as a temp file for intermediate building
mkdir -p "$WORK_DIR"
mkarchiso -v -w "$WORK_DIR" -o "$OUTPUT_DIR" "$PROFILE_DIR"
info "Cleaning up..."
rm -rf "$PROFILE_DIR"
rm -rf "$WORK_DIR"
chown_all "$SUDO_USER" "$OUTPUT_DIR" 

reop "Done! New ISO created in: $OUTPUT_DIR"
