#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/../../util_f"

if file_ex "$SCRIPT_DIR/../../..."; then
    . "$SCRIPT_DIR/../../..."
fi

# ARCHINSTALL SYSTEM SUBDEPS SCRIPT
PACKAGES=(
    # Required (core features)
    "git"
    "arch-install-scripts"
    "grub"
    "mkinitcpio"
    "pciutils"
    "dosfstools"
    # Optional (depending on options picked in archinstall)
    "btrfs-progs"
    #"cryptsetup"
    #"libfido2"
    # Core (sanity check)
    "coreutils"
    "e2fsprogs"
    "glibc"
    "shadow"
    "systemd"
    "util-linux"
    "python"
)
preop "Cheching system subdeps"
MISSING=()
for pkg in "${PACKAGES[@]}"; do
    if to_devnull pacman -Qi "$pkg"; then
        version=$(pacman -Qi "$pkg" | grep "^Version" | awk '{print $3}')
        preop "Found: $pkg ($version)"
    else
        postop "Missing: $pkg"
        MISSING+=("$pkg")
    fi
done
if [ ${#MISSING[@]} -gt 0 ]; then
    pacman -S --noconfirm ${MISSING[*]} || postop "Failed to install missing deps" && exit 1
else
    exit 0 
fi
